# Generated by Django 4.2.5 on 2023-09-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Catagory',
            new_name='category',
        ),
    ]
