# Generated by Django 4.2.5 on 2023-10-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product_qty',
        ),
    ]
